version: "3.3"
services:
    npm-app:
        build: .
        container_name: splite
        restart: unless-stopped
        environment:
            - SPLITE_TOKEN=ODMyNzUzNzk1ODU0MjM3Njk3.Gy2_9w.v20Z-e9dUCqu8GZobf-eNtA86oNnoSKKcY0BMQ
        volumes:
            -   ./splite-data:/home/node/app/data/db
