# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to Server

on:
  push:
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh deploy
        uses: appleboy/ssh-action@1d1b21ca96111b1eb4c03c21c14ebb971d2200f6
        with:
          # Private Key
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Remote host
          host: ${{ secrets.SSH_HOST }}
          # Remote user
          username: ${{ secrets.SSH_USER }}
          # Script
          script: |
            echo "Backing up database"
            cd /root/scripts/
            ./splite-data-backup.sh
            echo "Backing up database complete"
            echo "Applying Changes"
            cd /root/splite
            git pull -f
            echo "Applying Changes complete"
            
